version: "3.9"

services:
  web:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
